version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: heri-nginx
    # restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./config/conf.d:/etc/nginx/conf.d
      - ./code/html:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - mynetwork

  php-fpm:
    image: php:8.0-fpm
    container_name: heri-php-fpm
    volumes:
      - ./code:/var/www
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    container_name: heri-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project_db
      MYSQL_USER: heri
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: arm64v8/phpmyadmin:latest
    container_name: heri-phpmyadmin
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: heri
      PMA_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:

